---
title: "model_comparisons"
output: html_document
date: '2022-05-21'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
library(tidyverse)
library(maps)
library(ggplot2)

```

Load LM:
```{r}
lm_data = read_csv("time_df.csv")

lm_accuracy = lm_data$Time[6] # accuracy
lm_stability = c(lm_data$Time[8:12]) # 5 fold accuracy boxplot
lm_scalability = c(lm_data$Time[1:4]) # stability
```

Load RF:
```{r}
rf_data = read_csv("rf.csv")

rf_accuracy = rf_data$accuracy[1]
rf_stability = rf_data$accuracies[1:5]
rf_scalability = rf_data$time[1:4]
```

Load SVM:
```{r}
#temp values

svm_accuracy = 0.8
svm_stability = c(0.82, 0.81, 0.74, 0.8, 0.78)
svm_scalability = c(0.003, 0.022, 0.033, 0.233)
```

Accuracy:
```{r}
accuracies = data.frame(Accuracy = c(lm_accuracy, rf_accuracy, svm_accuracy),
                        Model = c("Logistic Regression", "Random Forest", "Support Vector Machine"))

accuracy <- ggplot(accuracies, aes(x = Model, y = Accuracy)) +
  geom_bar(stat = "identity", width = 0.5, fill = "steelblue") +
  theme_bw() +
  ggtitle("Accuracy of Model")

accuracy

```
Stability: using boxplots
```{r}
stabilities <- data.frame(model = rep(c('LM', 'RF', 'SVM'), each = 5),
                          accuracies = c(lm_stability, rf_stability, svm_stability))

 boxplot(stabilities$accuracies ~ stabilities$model,
        col='steelblue',
        main='Accuracies per fold',
        xlab='Model',
        ylab='Accuracies') 

```
Scalability: line graph of time
```{r}
scalabilities <- data.frame(model = rep(c('LM', 'RF', 'SVM'), each = 4),
                            train_size = as.factor(c('10%', '50%', '70%', '100%')),
                            time = c(lm_scalability, rf_scalability, svm_scalability))

scalabilities

ggplot(scalabilities, aes(x = train_size, y = time, group = model, colour = model)) +
  geom_line() 

  
```

